package ar.edu.unlu.zombi.modelo.enumerados;

public enum EventoGeneral {
	//Evento General
	MOSTRAR_PANTALLA_NOMBRES_JUGADORES_CARGADOS,
	MOSTRAR_PANTALLA_RONDA_JUGADORES,
	CONTINUAR_SIGUIENTE_TURNO_RONDA,
	FINAL_RONDA,
	MOSTRAR_PANTALLA_MENU_PRINCIPAL,
	PARTIDA_PERSISTIDA,
	ERROR_PARTIDA_PERSISTIDA,
	MOSTRAR_PANTALLA_NOMBRES_JUGADORES_PARTIDA_RECUPERADA,
	ERROR_PARTIDA_RECUPERADA,
	//Evento de jugadores
	ERROR_LIMITE_MINIMO_JUGADORES,
	ERROR_LIMITE_MAXIMO_JUGADORES,
	MOSTRAR_PANTALLA_CARGA_NOMBRE_JUGADOR,
	ERROR_VALIDACION_NOMBRE_JUGADOR,
	MOSTRAR_PANTALLA_ESPERA_JUGADORES,
	EVENTO_GLOBAL,
	ERROR_REMOTE_EXCEPTION,
	NO_SE_PUEDE_POR_ESTADO,
	JUGADOR_ADMIN_AGREGADO
}
